### ISSUE TITLE
'variable does not exist' error for growth model

### ISSUE THREAD

**Issue by wpetry** [Cristinabarber/Neighbor_Interactions#3]
I think I've found a typo in the second Stan chunk (growth model using `segment`). When run, the model throws the error
`Error in mod$fit_ptr() : 
  Exception: variable does not exist; processing stage=data initialization; variable name=size_observations; base type=vector_d  (in 'model57a344ef0e84_neigh_growth' at line 7)`.

The mismatch seems to be that the data list passes in
https://github.com/Cristinabarber/Neighbor_Interactions/blob/a8b60fad4093e2b629417f3ce522a04d6792fa74/plantInteractions.Rmd#L208-L209
But later the model refers to the same quantities (I think) by different names:
https://github.com/Cristinabarber/Neighbor_Interactions/blob/a8b60fad4093e2b629417f3ce522a04d6792fa74/plantInteractions.Rmd#L231-L232

I'm a bit confused by the naming, otherwise I would have submitted a PR. Thanks for publishing this case study!

**Comment by Cristinabarber** [comment]
Hi Will,

You are so right about that typo! Thanks a lot for noticing that and
letting me know I really appreciate. I will correct it asap.

Cristina
